version: "3"
services:
  server:
    build:
      dockerfile: dockerfile.dev
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    stdin_open: true
    build:
      dockerfile: dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
