version: "3"
services:
  server:
    build:
      dockerfile: dockerfile.dev
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    # expose:
    #   - 5000:5000
    ports:
      - "5000:5000"
  client:
    stdin_open: true
    build:
      dockerfile: dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    # expose:
    #   - 5173:5173
    ports:
      - "5173:5173"
